### ISSUE TITLE
要是能不依赖本地java环境就好了

### ISSUE THREAD

**Issue by ciqiu** [wuweiit/Bullet#3]
作者是否可以考虑下把客户端做成不依赖本地java环境，直接运行，把jre打包到exe，尽管可能体积会比较大，但是我觉得还是能接受！

**Comment by wuweiit** [comment]
因为这块我只做了客户端发版，还需要服务端支持，Client安装内网机器，Server安装外网服务器。
占时只做了linux支持，编译安装需要两个组件jdk+maven。
一键使用的版本等稳定了在做吧
